### ISSUE TITLE
apk?

### ISSUE THREAD

**Issue by dominictarr** [node-on-mobile/node-on-android#1]
just a reminder to post an APK because getting the build env setup is way too hard!

**Comment by ralphtheninja** [comment]
Post the apk where? Would be nice to have it on f-droid! My 2 satoshis.

**Comment by mafintosh** [comment]
I'm adding a basic RPC layer to make the webview load urls from node. Then I'll build and do a release here.

**Comment by fisch0920** [comment]
awesome project -- one suggestion would be to try and mimic the behavior and APIs of electron on desktop as closely as possible for node <-> webviews.

**Comment by dominictarr** [comment]
@fisch0920 yup definitely, but start with the simplest possible -down style api and then polyfil electron on top. Maybe not everything electron does, but there is probably a common subset that makes sense.

**Comment by mafintosh** [comment]
There is now a basic IPC layer in there (only loadUrl is supported right now) https://github.com/mafintosh/node-on-android/blob/master/app/src/main/assets/index.js#L4-L12

I'm gonna move it to an internal core module called `var android = require('node-on-android')`

**Comment by mafintosh** [comment]
@dominictarr https://github.com/mafintosh/node-on-android/releases/tag/pre-alpha

**Comment by sallespro** [comment]
@mafintosh i really liked the idea. @fisch0920 +1 to mimic Electron API. The WebView x node-on-android bridge is definitely the core, on thing to add is node running in the background, as a Service in Android does. This would make the project truly Mobile, allowing the use of async events generated by the Phone's sensors, radio & GPS. `node-on-android-sticky`

**Comment by dominictarr** [comment]
@abdulhannanali yes and no - cordova does let you write apps in javascript and run them on mobile, but it doesn't give you access to apis consistent to node, so you can take code that runs in the browser and run it on cordova easily enough, but you can't really take node code, and run it in cordova. But this will just run node on android, which will make that easy.

**Comment by abdulhannanali** [comment]
@dominictarr oh cool! That should be possible since Node uses Linux Kernel. Looking forward for this project to be successful. However, isn't node quite huge and a memory consumer for mobile devices?

**Comment by dominictarr** [comment]
@abdulhannanali that is true, but it is not worse than a browser, and people still use browsers on phones, and many apps have imbedded browsers!
It's possible to write memory javascript apps, it just takes a bit of effort (as it does with any other language) and phones are getting surprisingly large these days. I've been running a full in a container on my phone using https://github.com/meefik/linuxdeploy it's worked great, but this will allow you to easily build apps for release, where as linuxdeploy requires a rooted phone.

**Comment by aschrijver** [comment]
Anyone has experience with https://github.com/eclipsesource/J2V8 ?

Looks like it can run node on android as well (not sure if enabled by default).

**Comment by aschrijver** [comment]
Also along similar lines to this project, I found this: https://github.com/dna2github/NodeBase

**Comment by mafintosh** [comment]
added apk builder

**Comment by aschrijver** [comment]
This is closed, but I just wanted to add one related resource for reference/learning/fyi:
https://github.com/LiquidPlayer/LiquidCore
